#### 10 Commonly Used Attributes

1. Second Derivative = Continuity, facies

2. Reflection Intensity = Impedance contrasts, facies

3. Envelope = Water saturation, facies changes, fault, changes in lithofacies and bed thickness, hydrocarbon

4. Instantaneous Frequency = Hydrocarbon reservoir, fracture, interface, change in facies

5. Instantaneous Phase = Fault and pinch-out, hydrocarbon reservoir trap, facies changes, continuities, terminations, interfaces

6. Sweetness = Water saturation, indicator of clean and or relatively thicker ‘thin’ sands like deltaic deposits or channel sands, potential hydrocarbon reservoir (similar to horizon slices)

7. Instantaneous Bandwidth = Facies

8. Cosine Instantaneous Phase = Structural delineation, facies

9. Dominant Frequency = Facies 

10. Semblance (untuk menghitung Coherence) = Discontinuity = kebalikan Variance (low coherence = high variance) = Stratigraphic discontinuities (fault, fractures, and channels), salt domes detection, reveal faults and fracture zones, stratigraphic features such as channels, deltaic deposits, turbidites, and slope and basin floor fans, facies changes

#### .segy --> segyio --> Matplotlib --> .png

In [2]:
import segyio
import os
import matplotlib.pyplot as plt

segy_dir = 'SEGY'
assert os.path.exists(segy_dir), 'Dataset tidak ditemukan!'

In [3]:
amp_in_dir = os.path.join(segy_dir, 'TrainingData_Image.segy')
sd_in_dir = os.path.join(segy_dir, 'second-derivative.segy')
ri_in_dir = os.path.join(segy_dir, 'reflection-intensity.segy')
e_in_dir = os.path.join(segy_dir, 'envelope.segy')
ifreq_in_dir = os.path.join(segy_dir, 'instantaneous-frequency.segy')
ip_in_dir = os.path.join(segy_dir, 'instantaneous-phase.segy')
s_in_dir = os.path.join(segy_dir, 'sweetness.segy')
ib_in_dir = os.path.join(segy_dir, 'instantaneous-bandwith.segy')
cip_in_dir = os.path.join(segy_dir, 'cosine-phase.segy')
dfreq_in_dir = os.path.join(segy_dir, 'dominant-frequency.segy')
sem_in_dir = os.path.join(segy_dir, 'variance-edge-method.segy')

for dir in [amp_in_dir, sd_in_dir, ri_in_dir, e_in_dir, ifreq_in_dir, ip_in_dir, s_in_dir, ib_in_dir, cip_in_dir, dfreq_in_dir, sem_in_dir]:
    assert os.path.isfile(dir), "Dataset {} tidak ditemukan!".format(dir.split(os.sep)[1])

In [4]:
out_dir = os.path.join('output', 'Images')
if not os.path.exists(out_dir):
    os.makedirs(out_dir)

amp_out_dir = os.path.join(out_dir, 'Amplitude')
sd_out_dir = os.path.join(out_dir, 'Second Derivative')
ri_out_dir = os.path.join(out_dir, 'Reflection Intensity')
e_out_dir = os.path.join(out_dir, 'Envelope')
ifreq_out_dir = os.path.join(out_dir, 'Instantaneous Frequency')
ip_out_dir = os.path.join(out_dir, 'Instantaneous Phase')
s_out_dir = os.path.join(out_dir, 'Sweetness')
ib_out_dir = os.path.join(out_dir, 'Instantaneous Bandwith')
cip_out_dir = os.path.join(out_dir, 'Cosine Instantaneous Phase')
dfreq_out_dir = os.path.join(out_dir, 'Dominant Frequency')
sem_out_dir = os.path.join(out_dir, 'Semblance')

for dir in [amp_out_dir, sd_out_dir, ri_out_dir, e_out_dir, ifreq_out_dir, ip_out_dir, s_out_dir, ib_out_dir, cip_out_dir, dfreq_out_dir, sem_out_dir]:
    if not os.path.exists(dir):
        os.mkdir(dir)
        os.mkdir(os.path.join(dir, 'Inlines'))
        os.mkdir(os.path.join(dir, 'Crosslines'))

In [7]:
data_dir_dict = {
    'amp': [amp_in_dir, amp_out_dir],
    'sd': [sd_in_dir, sd_out_dir],
    'ri': [ri_in_dir, ri_out_dir],
    'e': [e_in_dir, e_out_dir],
    'ifreq': [ifreq_in_dir, ifreq_out_dir],
    'ip': [ip_in_dir, ip_out_dir],
    's': [s_in_dir, s_out_dir],
    'ib': [ib_in_dir, ib_out_dir],
    'cip': [cip_in_dir, cip_out_dir],
    'dfreq': [dfreq_in_dir, dfreq_out_dir],
    'sem': [sem_in_dir, sem_out_dir]
}

n_inlines, n_crosslines = (590, 782)
print(f'Jumlah Inlines: {n_inlines}')
print(f'Jumlah Crosslines: {n_crosslines}')

Jumlah Inlines: 590
Jumlah Crosslines: 782


In [6]:
# for k, v in data_dir_dict.items():
#     # k = attributes name => unused
#     # v[0] = data_in_dir
#     # v[1] = data_out_dir

#     data = segyio.tools.cube(v[0]) # Every data dimension = (590, 782, 1006)

#     # Save ilines into PNG format
#     for i in range(n_inlines):
#         file_name = os.path.join(v[1], 'Inlines', '{}.png'.format(str(i+1)))
#         plt.imsave(file_name, data[i].T)

#     # Save ilines into PNG format
#     for i in range(n_crosslines):
#         file_name = os.path.join(v[1], 'Crosslines', '{}.png'.format(str(i+1)))
#         plt.imsave(file_name, data[:, i, :].T)

#     # Clean data object in memory
#     del data



for _, (data_in_dir, data_out_dir) in data_dir_dict.items():
    data = segyio.tools.cube(data_in_dir) # Every data dimension = (590, 782, 1006)

    # Save ilines into PNG format
    for i in range(n_inlines):
        file_name = os.path.join(data_out_dir, 'Inlines', '{}.png'.format(str(i+1)))
        plt.imsave(file_name, data[i].T)

    # Save ilines into PNG format
    for i in range(n_crosslines):
        file_name = os.path.join(data_out_dir, 'Crosslines', '{}.png'.format(str(i+1)))
        plt.imsave(file_name, data[:, i, :].T)

    # Clean data object in memory
    del data

***

#### Extract Labels

In [5]:
import segyio
import os
import matplotlib.pyplot as plt



labels_in_dir = '../dataset/TrainingData_Labels.segy'
assert os.path.isfile(labels_in_dir), 'Dataset label tidak ditemukan!'

out_dir = os.path.join('output', 'Images')
if not os.path.exists(out_dir):
    os.makedirs(out_dir)

labels_out_dir = os.path.join(out_dir, 'Labels')
if not os.path.exists(labels_out_dir):
    os.mkdir(labels_out_dir)
    os.mkdir(os.path.join(labels_out_dir, 'Inlines'))
    os.mkdir(os.path.join(labels_out_dir, 'Crosslines'))



data = segyio.tools.cube(labels_in_dir)
n_inlines, n_crosslines = (590, 782)

for i in range(n_inlines):
    file_name = os.path.join(labels_out_dir, 'Inlines', '{}.png'.format(str(i+1)))
    plt.imsave(file_name, data[i].T)

for i in range(n_crosslines):
    file_name = os.path.join(labels_out_dir, 'Crosslines', '{}.png'.format(str(i+1)))
    plt.imsave(file_name, data[:, i, :].T)

del data

***

#### Reading image dataset (inline)

In [11]:
import os
from PIL import Image as im
import cv2

input_image_dir = os.path.join('output', 'Images', 'Amplitude', 'Inlines', '2.png')
assert os.path.isfile(input_image_dir), 'Gambar tidak ditemukan!'

In [13]:
image_pil = im.open(input_image_dir)
image_cv = cv2.imread(input_image_dir)

print(f'PIL:\n{type(image_pil)}, {image_pil.size}\n')
print(f'OpenCV:\n{type(image_cv)}, {image_cv.shape}\n')

image_cv_no_C = image_cv[:, :, 0].T
print(image_cv_no_C.shape)

PIL:
<class 'PIL.PngImagePlugin.PngImageFile'>, (782, 1006)

OpenCV:
<class 'numpy.ndarray'>, (1006, 782, 3)

(782, 1006)


In [9]:
coba = image_cv.T
print(coba.shape)

(3, 782, 1006)


#### Catatan lainnya

TensorFlow dan Keras:
- Kelebihan: Kemudahan penggunaan dengan Keras, ekosistem besar, dukungan komunitas, deployment mudah.
- Kelemahan: Kurva pembelajaran curam, overhead komputasi, debugging kurang intuitif, ukuran dan kompleksitas framework.

PyTorch:
- Kelebihan: Fleksibilitas, dynamic computation graph, intuitif untuk penelitian, dukungan komunitas yang berkembang cepat.
- Kelemahan: Perubahan besar di rilis baru, ekosistem lebih kecil, deployment lebih kompleks.

OpenCV (cv2):
- Kelebihan: Sangat fleksibel untuk operasi gambar dan video, kuat untuk pra-pemrosesan gambar.
- Kelemahan: Tidak spesifik untuk deep learning, integrasi lebih rumit, membutuhkan lebih banyak kode untuk pra-pemrosesan.

Pillow (PIL):
- Kelebihan: Mudah digunakan untuk operasi dasar pada gambar, integrasi dengan NumPy.
- Kelemahan: Fitur terbatas, performa kurang optimal untuk pengolahan gambar skala besar, tidak spesifik untuk deep learning.

In [ ]:
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# transform = transforms.Compose([
#     transforms.Resize((256, 256)),
#     transforms.ToTensor()
# ])

# Harus ke dalam class sehingga dalam folder Inlines,
# buat folder class0 dan isi dgn gambar, begitu jg untuk class1 dan seterusnya
# dataset = datasets.ImageFolder('path/to/directory', transform=transform)
images_dir = os.path.join('output', 'Images', 'Amplitude', 'Inlines')
dataset = datasets.ImageFolder(images_dir) # Output: torchvision.datasets.folder.ImageFolder
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

# Contoh iterasi melalui DataLoader
for images, labels in dataloader:
    print(images.shape, labels.shape)

In [14]:
import numpy as np

array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Mentansposisi dengan urutan sumbu tertentu
transposed_array_3d = np.transpose(array_3d, (1, 0, 2))

print("\nOriginal 3D array:")
print(array_3d)
print("\nTransposed 3D array with specific axes order using np.transpose:")
print(transposed_array_3d)

# [
#     [
#         [1 2] # 000 001
#         [3 4] # 010 011
#     ]

#     [
#         [5 6] # 100 101
#         [7 8] # 110 111
#     ]
# ]

# ---

# [
#     [
#         [1 2] # 000 001
#         [5 6] # 100 101
#     ]

#     [
#         [3 4] # 010 011
#         [7 8] # 110 111
#     ]
# ]


Original 3D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Transposed 3D array with specific axes order using np.transpose:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
